// Code generated by "stringer -type=SecretStoreResult"; DO NOT EDIT.

package secret_store

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[InvalidCallingAssembly-1]
	_ = x[CreateDatabaseError-2]
	_ = x[UseDatabaseError-3]
	_ = x[CreateTableError-4]
	_ = x[CreateIndexError-5]
	_ = x[ConnectionError-6]
	_ = x[TransactionError-7]
	_ = x[InvalidVaultID-8]
	_ = x[InvalidParams-9]
	_ = x[InsufficientPermissions-10]
	_ = x[CryptoFailure-11]
	_ = x[DeleteSecretFailed-12]
	_ = x[AddSecretFailed-13]
	_ = x[RetrieveSecretFailed-14]
	_ = x[RetrieveSecretTypeFailed-15]
	_ = x[GetNextVaultIDFailed-16]
	_ = x[DisassociateFailed-17]
	_ = x[OwnerLookupFailed-18]
	_ = x[AssociateDataFailed-19]
	_ = x[LookupFailed-20]
	_ = x[InvalidKey-21]
	_ = x[QueryError-22]
	_ = x[SecurityGroupNotImplemented-23]
}

const _SecretStoreResult_name = "SuccessInvalidCallingAssemblyCreateDatabaseErrorUseDatabaseErrorCreateTableErrorCreateIndexErrorConnectionErrorTransactionErrorInvalidVaultIDInvalidParamsInsufficientPermissionsCryptoFailureDeleteSecretFailedAddSecretFailedRetrieveSecretFailedRetrieveSecretTypeFailedGetNextVaultIDFailedDisassociateFailedOwnerLookupFailedAssociateDataFailedLookupFailedInvalidKeyQueryErrorSecurityGroupNotImplemented"

var _SecretStoreResult_index = [...]uint16{0, 7, 29, 48, 64, 80, 96, 111, 127, 141, 154, 177, 190, 208, 223, 243, 267, 287, 305, 322, 341, 353, 363, 373, 400}

func (i SecretStoreResult) String() string {
	if i < 0 || i >= SecretStoreResult(len(_SecretStoreResult_index)-1) {
		return "SecretStoreResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SecretStoreResult_name[_SecretStoreResult_index[i]:_SecretStoreResult_index[i+1]]
}
