// Code generated by "stringer -type=ConfigResult"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-1]
}

const _ConfigResult_name = "Success"

var _ConfigResult_index = [...]uint8{0, 7}

func (i ConfigResult) String() string {
	i -= 1
	if i < 0 || i >= ConfigResult(len(_ConfigResult_index)-1) {
		return "ConfigResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ConfigResult_name[_ConfigResult_index[i]:_ConfigResult_index[i+1]]
}
